[project]
name = "06-frontend-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vicc9", email = "geegle2@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
]

[project.scripts]
06-frontend-ui = "06_frontend_ui:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
